excluded:
  - Pods
line_length:
  warning: 10
  #error: 600
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ### works up until this config rule
  ignores_interpolated_strings: true

analyzer_rules:
  - unused_import
  - unused_private_declaration
opt_in_rules:
  - anyobject_protocol
  - array_init
  #- attributes
  - closure_end_indentation
  - closure_spacing
  #- collection_alignment
  - contains_over_first_not_nil
  #- empty_count
  - empty_string
  - empty_xctest_method
  #- explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  #- file_header
  - file_name
  - first_where
  - identical_operands
  - joined_default_parameter
  - let_var_whitespace
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - nimble_operator
  - number_separator
  - object_literal
  #- operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  #- prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  #- sorted_imports
  - static_operator
  - unavailable_function
  #- unneeded_parentheses_in_closure_argument
  #- untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  #- vertical_whitespace_closing_braces
  #- vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

identifier_name:
  excluded:
    - id
    - Carthage
    - Pods
number_separator:
  minimum_length: 5
file_name:
  excluded:
    - main.swift
    - LinuxMain.swift
    - TestHelpers.swift
    - shim.swift
    - AutomaticRuleTests.generated.swift
cyclomatic_complexity:
  ignores_case_statements: true
disabled_rules:
  - unused_optional_binding
  - collection_alignment
  - vertical_parameter_alignment_on_call
  - function_parameter_count
  - object_literal
  - empty_enum_arguments
  - shorthand_operator
  - force_cast
  - function_body_length
  - vertical_whitespace
  - trailing_newline
  - trailing_whitespace
  - file_header
  - empty_count
  - identifier_name
  - legacy_constructor
  - file_name
  - unused_closure_parameter
  - implicit_getter
  - control_statement
  - line_length
  - type_name
  - pattern_matching_keywords
  - fatal_error
  - unavailable_function
custom_rules:
  rule_id:
    included: Source/SwiftLintFramework/Rules/.+/\w+\.swift
    name: Rule ID
    message: Rule IDs must be all lowercase, snake case and not end with `rule`
    regex: identifier:\s*("\w+_rule"|"\S*[^a-z_]\S*")
    severity: error
  # fatal_error:
  #   name: Fatal Error
  #   excluded: "Tests/*"
  #   message: Prefer using `queuedFatalError` over `fatalError` to avoid leaking compiler host machine paths.
  #   regex: \bfatalError\b
  #   match_kinds:
  #     - identifier
  #   severity: error
  rule_test_function:
    included: Tests/SwiftLintFrameworkTests/RulesTests.swift
    name: Rule Test Function
    message: Rule Test Function mustn't end with `rule`
    regex: func\s*test\w+(r|R)ule\(\)
    severity: error
